// Beginner Dutch vocabulary, grouped by theme. [dutch, english, example?]
type Raw = [string, string, string?]

const data: Record<string, Raw[]> = {
  Greetings: [
    ['hallo', 'hello'],
    ['hoi', 'hi'],
    ['goedemorgen', 'good morning'],
    ['goedemiddag', 'good afternoon'],
    ['goedenavond', 'good evening'],
    ['goedenacht', 'good night'],
    ['tot ziens', 'goodbye'],
    ['doei', 'bye'],
    ['dank je wel', 'thank you'],
    ['alsjeblieft', 'please / here you go'],
    ['sorry', 'sorry'],
    ['ja', 'yes'],
    ['nee', 'no'],
    ['misschien', 'maybe'],
    ['welkom', 'welcome'],
  ],
  Numbers: [
    ['nul', 'zero'],
    ['een', 'one'],
    ['twee', 'two'],
    ['drie', 'three'],
    ['vier', 'four'],
    ['vijf', 'five'],
    ['zes', 'six'],
    ['zeven', 'seven'],
    ['acht', 'eight'],
    ['negen', 'nine'],
    ['tien', 'ten'],
    ['elf', 'eleven'],
    ['twaalf', 'twelve'],
    ['twintig', 'twenty'],
    ['honderd', 'hundred'],
    ['duizend', 'thousand'],
  ],
  Colors: [
    ['rood', 'red'],
    ['blauw', 'blue'],
    ['groen', 'green'],
    ['geel', 'yellow'],
    ['zwart', 'black'],
    ['wit', 'white'],
    ['oranje', 'orange'],
    ['paars', 'purple'],
    ['roze', 'pink'],
    ['bruin', 'brown'],
    ['grijs', 'grey'],
  ],
  Family: [
    ['moeder', 'mother'],
    ['vader', 'father'],
    ['zus', 'sister'],
    ['broer', 'brother'],
    ['dochter', 'daughter'],
    ['zoon', 'son'],
    ['oma', 'grandma'],
    ['opa', 'grandpa'],
    ['vriend', 'friend (m)'],
    ['vriendin', 'friend (f) / girlfriend'],
    ['kind', 'child'],
    ['man', 'man / husband'],
    ['vrouw', 'woman / wife'],
  ],
  Food: [
    ['brood', 'bread'],
    ['kaas', 'cheese'],
    ['appel', 'apple'],
    ['ei', 'egg'],
    ['vlees', 'meat'],
    ['vis', 'fish'],
    ['groente', 'vegetable'],
    ['fruit', 'fruit'],
    ['aardappel', 'potato'],
    ['rijst', 'rice'],
    ['boter', 'butter'],
    ['suiker', 'sugar'],
    ['zout', 'salt'],
    ['ontbijt', 'breakfast'],
    ['lunch', 'lunch'],
    ['avondeten', 'dinner'],
  ],
  Drinks: [
    ['water', 'water'],
    ['koffie', 'coffee'],
    ['thee', 'tea'],
    ['melk', 'milk'],
    ['bier', 'beer'],
    ['wijn', 'wine'],
    ['sap', 'juice'],
    ['frisdrank', 'soft drink'],
  ],
  Time: [
    ['maandag', 'Monday'],
    ['dinsdag', 'Tuesday'],
    ['woensdag', 'Wednesday'],
    ['donderdag', 'Thursday'],
    ['vrijdag', 'Friday'],
    ['zaterdag', 'Saturday'],
    ['zondag', 'Sunday'],
    ['vandaag', 'today'],
    ['morgen', 'tomorrow'],
    ['gisteren', 'yesterday'],
    ['week', 'week'],
    ['maand', 'month'],
    ['jaar', 'year'],
    ['uur', 'hour'],
    ['minuut', 'minute'],
    ['nu', 'now'],
  ],
  Verbs: [
    ['zijn', 'to be'],
    ['hebben', 'to have'],
    ['gaan', 'to go'],
    ['komen', 'to come'],
    ['eten', 'to eat'],
    ['drinken', 'to drink'],
    ['slapen', 'to sleep'],
    ['werken', 'to work'],
    ['spreken', 'to speak'],
    ['lezen', 'to read'],
    ['schrijven', 'to write'],
    ['zien', 'to see'],
    ['horen', 'to hear'],
    ['lopen', 'to walk'],
    ['kopen', 'to buy'],
    ['maken', 'to make'],
    ['weten', 'to know'],
    ['willen', 'to want'],
    ['kunnen', 'to be able to'],
    ['houden van', 'to love'],
  ],
  Animals: [
    ['hond', 'dog'],
    ['kat', 'cat'],
    ['vogel', 'bird'],
    ['paard', 'horse'],
    ['koe', 'cow'],
    ['varken', 'pig'],
    ['schaap', 'sheep'],
    ['kip', 'chicken'],
    ['muis', 'mouse'],
    ['konijn', 'rabbit'],
  ],
  Body: [
    ['hoofd', 'head'],
    ['oog', 'eye'],
    ['oor', 'ear'],
    ['neus', 'nose'],
    ['mond', 'mouth'],
    ['hand', 'hand'],
    ['voet', 'foot'],
    ['arm', 'arm'],
    ['been', 'leg'],
    ['hart', 'heart'],
  ],
  Home: [
    ['huis', 'house'],
    ['deur', 'door'],
    ['raam', 'window'],
    ['tafel', 'table'],
    ['stoel', 'chair'],
    ['bed', 'bed'],
    ['keuken', 'kitchen'],
    ['badkamer', 'bathroom'],
    ['slaapkamer', 'bedroom'],
    ['tuin', 'garden'],
    ['licht', 'light'],
    ['sleutel', 'key'],
  ],
  Weather: [
    ['zon', 'sun'],
    ['regen', 'rain'],
    ['wind', 'wind'],
    ['sneeuw', 'snow'],
    ['wolk', 'cloud'],
    ['warm', 'warm'],
    ['koud', 'cold'],
    ['mooi weer', 'nice weather'],
  ],
  Travel: [
    ['trein', 'train'],
    ['fiets', 'bicycle'],
    ['auto', 'car'],
    ['bus', 'bus'],
    ['vliegtuig', 'airplane'],
    ['station', 'station'],
    ['straat', 'street'],
    ['stad', 'city'],
    ['links', 'left'],
    ['rechts', 'right'],
    ['rechtdoor', 'straight ahead'],
    ['kaartje', 'ticket'],
  ],
  Adjectives: [
    ['groot', 'big'],
    ['klein', 'small'],
    ['goed', 'good'],
    ['slecht', 'bad'],
    ['nieuw', 'new'],
    ['oud', 'old'],
    ['mooi', 'beautiful'],
    ['lelijk', 'ugly'],
    ['snel', 'fast'],
    ['langzaam', 'slow'],
    ['gemakkelijk', 'easy'],
    ['moeilijk', 'difficult'],
    ['veel', 'much / many'],
    ['weinig', 'few'],
  ],
  Questions: [
    ['wat', 'what'],
    ['wie', 'who'],
    ['waar', 'where'],
    ['wanneer', 'when'],
    ['waarom', 'why'],
    ['hoe', 'how'],
    ['hoeveel', 'how much'],
    ['welke', 'which'],
  ],
  Pronouns: [
    ['ik', 'I'],
    ['jij', 'you'],
    ['hij', 'he'],
    ['zij', 'she / they'],
    ['wij', 'we'],
    ['het', 'it'],
    ['mijn', 'my'],
    ['jouw', 'your'],
  ],
  Phrases: [
    ['hoe gaat het?', 'how are you?'],
    ['goed, dank je', 'good, thank you'],
    ['hoe heet je?', 'what is your name?'],
    ['ik heet...', 'my name is...'],
    ['ik begrijp het niet', "I don't understand"],
    ['spreek je Engels?', 'do you speak English?'],
    ['ik weet het niet', "I don't know"],
    ['tot morgen', 'see you tomorrow'],
    ['veel succes', 'good luck'],
    ['geen probleem', 'no problem'],
  ],
}

export interface SeedWord {
  dutch: string
  english: string
  theme: string
  example?: string
}

export const VOCAB_SEED: SeedWord[] = Object.entries(data).flatMap(
  ([theme, words]) =>
    words.map(([dutch, english, example]) => ({ dutch, english, theme, example })),
)

export const VOCAB_THEMES = Object.keys(data)
